#!/bin/bash
   BACKUP_DIR="/backup/jenkins_auto_backup_$(date +%F)"
   sudo mkdir -p $BACKUP_DIR
   sudo cp -r /var/lib/jenkins/* $BACKUP_DIR
   sudo tar -czf $BACKUP_DIR.tar.gz $BACKUP_DIR
   sudo rm -rf $BACKUP_DIR
